ACCEPTANCE: AzureBlobStorage CreateDirectorySasToken
NHSISL/ISL.Providers.Storages pull request #54
Opened 2024-12-11 13:19 UTC by MichaelOSullivanAnswer

CLOSES #AB17745

2024-12-11 15:34 UTC, cjdutoit commented on ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Logic.CreateDirectorySasTokenAsync.cs
>                          .ReturnsAsync(outputSasToken);
```suggestion
            this.storageProviderMock.Setup(service =>
                service.CreateDirectorySasTokenAsync(inputContainer, inputDirectoryPath, inputAccessPolicyIdentifier))
                        .ReturnsAsync(outputSasToken);
```

2024-12-11 15:34 UTC, cjdutoit commented on ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Logic.CreateDirectorySasTokenAsync.cs
> +                    inputContainer, inputDirectoryPath, inputAccessPolicyIdentifier);
```suggestion
            string actualSasToken = await this.storageAbstractionProvider
                .CreateDirectorySasTokenAsync(inputContainer, inputDirectoryPath, inputAccessPolicyIdentifier);
```

2024-12-11 15:35 UTC, cjdutoit commented on ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Logic.CreateDirectorySasTokenAsync.cs
>                          Times.Once);
```suggestion
            this.storageProviderMock.Verify(service =>
                service.CreateDirectorySasTokenAsync(inputContainer, inputDirectoryPath, inputAccessPolicyIdentifier),
                    Times.Once);
```

2024-12-11 15:35 UTC, cjdutoit commented on ISL.Providers.Storages.AzureBlobStorage/Brokers/Storages/Blobs/BlobStorageBroker.cs
> +            string container, string directoryPath, string accessPolicyIdentifier)
fix

2024-12-11 15:36 UTC, cjdutoit commented on ISL.Providers.Storages.AzureBlobStorage/Providers/AzureBlobStorage/AzureBlobStorageProvider.cs
> +             string container, string directoryPath, string accessPolicyIdentifier)
fix

2024-12-11 15:36 UTC, cjdutoit commented on ISL.Providers.Storages.AzureBlobStorage/Providers/AzureBlobStorage/AzureBlobStorageProvider.cs
> +                    container, directoryPath, accessPolicyIdentifier);
fix

2024-12-11 15:36 UTC, cjdutoit commented on ISL.Providers.Storages.AzureBlobStorage/Services/Foundations/Storages/IStorageService.cs
> +             string container, string directoryPath, string accessPolicyIdentifier);
fix

2024-12-11 15:36 UTC, cjdutoit commented on ISL.Providers.Storages.AzureBlobStorage/Services/Foundations/Storages/StorageService.Validations.cs
> +            string container, string directoryPath, string accessPolicyIdentifier)
fix

2024-12-11 15:37 UTC, cjdutoit commented on ISL.Providers.Storages.AzureBlobStorage/Services/Foundations/Storages/StorageService.cs
> +             string container, string directoryPath, string accessPolicyIdentifier) =>
fix

2024-12-11 15:37 UTC, cjdutoit commented on ISL.Providers.Storages.AzureBlobStorage/Services/Foundations/Storages/StorageService.cs
> +                container, directoryPath, accessPolicyIdentifier);
fix

2024-12-11 15:38 UTC, cjdutoit commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Exceptions.CreateDirectorySasToken.cs
> +                    inputContainer, inputDirectoryPath, inputAccessPolicyIdentifier))
fix

2024-12-11 15:38 UTC, cjdutoit commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Exceptions.CreateDirectorySasToken.cs
> +                    inputContainer, inputDirectoryPath, inputAccessPolicyIdentifier);
fix

2024-12-11 15:38 UTC, cjdutoit commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Exceptions.CreateDirectorySasToken.cs
> +                    inputContainer, inputDirectoryPath, inputAccessPolicyIdentifier),
fix

2024-12-11 15:38 UTC, cjdutoit commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Exceptions.CreateDirectorySasToken.cs
> +                    inputContainer, inputDirectoryPath, inputAccessPolicyIdentifier))
fix

2024-12-11 15:38 UTC, cjdutoit commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Exceptions.CreateDirectorySasToken.cs
> +                    inputContainer, inputDirectoryPath, inputAccessPolicyIdentifier);
fix

2024-12-11 15:38 UTC, cjdutoit commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Exceptions.CreateDirectorySasToken.cs
> +                    inputContainer, inputDirectoryPath, inputAccessPolicyIdentifier),
fix

2024-12-11 15:38 UTC, cjdutoit commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Exceptions.CreateDirectorySasToken.cs
> +                    inputContainer, inputDirectoryPath, inputAccessPolicyIdentifier))
fix

2024-12-11 15:38 UTC, cjdutoit commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Exceptions.CreateDirectorySasToken.cs
>              // when
fix

2024-12-11 15:39 UTC, cjdutoit commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Exceptions.CreateDirectorySasToken.cs
> +                    inputContainer, inputDirectoryPath, inputAccessPolicyIdentifier),
fix

2024-12-11 15:39 UTC, cjdutoit commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Logic.CreateDirectorySasToken.cs
> +                    inputContainer, inputDirectoryPath, inputAccessPolicyIdentifier))
fix

2024-12-11 15:39 UTC, cjdutoit commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Logic.CreateDirectorySasToken.cs
> +                    inputContainer, inputDirectoryPath, inputAccessPolicyIdentifier);
fix

2024-12-11 15:39 UTC, cjdutoit commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Logic.CreateDirectorySasToken.cs
> +                    inputContainer, inputDirectoryPath, inputAccessPolicyIdentifier),
fix

2024-12-11 15:39 UTC, cjdutoit commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Storages/StorageTests.Exceptions.CreateDirectorySasToken.cs
> +                    someContainer, someDirectoryPath, someAccessPolicyIdentifier))
fix

2024-12-11 15:39 UTC, cjdutoit commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Storages/StorageTests.Exceptions.CreateDirectorySasToken.cs
> +                    someContainer, someDirectoryPath, someAccessPolicyIdentifier);
fix

2024-12-11 15:40 UTC, cjdutoit commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Storages/StorageTests.Exceptions.CreateDirectorySasToken.cs
> +                    someContainer, someDirectoryPath, someAccessPolicyIdentifier),
fix

2024-12-11 15:40 UTC, cjdutoit commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Storages/StorageTests.Exceptions.CreateDirectorySasToken.cs
> +                broker.CreateDirectorySasTokenAsync(
fix

2024-12-11 15:40 UTC, cjdutoit commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Storages/StorageTests.Exceptions.CreateDirectorySasToken.cs
> +                    someContainer, someDirectoryPath, someAccessPolicyIdentifier);
fix

2024-12-11 15:40 UTC, cjdutoit commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Storages/StorageTests.Exceptions.CreateDirectorySasToken.cs
> +                    someContainer, someDirectoryPath, someAccessPolicyIdentifier))
fix

2024-12-11 15:41 UTC, cjdutoit commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Storages/StorageTests.Exceptions.CreateDirectorySasToken.cs
> +                    someContainer, someDirectoryPath, someAccessPolicyIdentifier);
fix

2024-12-11 15:41 UTC, cjdutoit commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Storages/StorageTests.Logic.CreateDirectorySasToken.cs
> +                inputContainer, inputDirectoryPath, inputAccessPolicyIdentifier);
fix

2024-12-11 15:42 UTC, cjdutoit commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Storages/StorageTests.Validations.CreateDirectorySasToken.cs
> +                    invalidContainer, invalidDirectoryPath, invalidAccessPolicyIdentifier);
fix

2024-12-11 15:42 UTC, cjdutoit requested changes
Code cleanups needed

2024-12-12 11:35 UTC, MichaelOSullivanAnswer commented on ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Logic.CreateDirectorySasTokenAsync.cs
>                          .ReturnsAsync(outputSasToken);
updated

2024-12-12 11:36 UTC, MichaelOSullivanAnswer commented on ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Logic.CreateDirectorySasTokenAsync.cs
> +                    inputContainer, inputDirectoryPath, inputAccessPolicyIdentifier);
updated

2024-12-12 11:36 UTC, MichaelOSullivanAnswer commented on ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Logic.CreateDirectorySasTokenAsync.cs
>                          Times.Once);
updated

2024-12-12 11:37 UTC, MichaelOSullivanAnswer commented on ISL.Providers.Storages.AzureBlobStorage/Brokers/Storages/Blobs/BlobStorageBroker.cs
> +            string container, string directoryPath, string accessPolicyIdentifier)
updated

2024-12-12 11:37 UTC, MichaelOSullivanAnswer commented on ISL.Providers.Storages.AzureBlobStorage/Providers/AzureBlobStorage/AzureBlobStorageProvider.cs
> +                    container, directoryPath, accessPolicyIdentifier);
updated

2024-12-12 11:38 UTC, MichaelOSullivanAnswer commented on ISL.Providers.Storages.AzureBlobStorage/Services/Foundations/Storages/StorageService.Validations.cs
> +            string container, string directoryPath, string accessPolicyIdentifier)
updated

2024-12-12 11:38 UTC, MichaelOSullivanAnswer commented on ISL.Providers.Storages.AzureBlobStorage/Services/Foundations/Storages/StorageService.cs
> +                container, directoryPath, accessPolicyIdentifier);
updated

2024-12-12 11:38 UTC, MichaelOSullivanAnswer commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Exceptions.CreateDirectorySasToken.cs
> +                    inputContainer, inputDirectoryPath, inputAccessPolicyIdentifier))
updated

2024-12-12 11:38 UTC, MichaelOSullivanAnswer commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Exceptions.CreateDirectorySasToken.cs
> +                    inputContainer, inputDirectoryPath, inputAccessPolicyIdentifier);
updated

2024-12-12 11:38 UTC, MichaelOSullivanAnswer commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Exceptions.CreateDirectorySasToken.cs
> +                    inputContainer, inputDirectoryPath, inputAccessPolicyIdentifier),
updated

2024-12-12 11:38 UTC, MichaelOSullivanAnswer commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Exceptions.CreateDirectorySasToken.cs
> +                    inputContainer, inputDirectoryPath, inputAccessPolicyIdentifier))
updated

2024-12-12 11:38 UTC, MichaelOSullivanAnswer commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Exceptions.CreateDirectorySasToken.cs
> +                    inputContainer, inputDirectoryPath, inputAccessPolicyIdentifier);
updated

2024-12-12 11:39 UTC, MichaelOSullivanAnswer commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Exceptions.CreateDirectorySasToken.cs
> +                    inputContainer, inputDirectoryPath, inputAccessPolicyIdentifier),
updated

2024-12-12 11:39 UTC, MichaelOSullivanAnswer commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Exceptions.CreateDirectorySasToken.cs
> +                    inputContainer, inputDirectoryPath, inputAccessPolicyIdentifier))
updated

2024-12-12 11:40 UTC, MichaelOSullivanAnswer commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Exceptions.CreateDirectorySasToken.cs
>              // when
updated

2024-12-12 11:40 UTC, MichaelOSullivanAnswer commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Logic.CreateDirectorySasToken.cs
> +                    inputContainer, inputDirectoryPath, inputAccessPolicyIdentifier))
updated

2024-12-12 11:40 UTC, MichaelOSullivanAnswer commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Logic.CreateDirectorySasToken.cs
> +                    inputContainer, inputDirectoryPath, inputAccessPolicyIdentifier);
updated

2024-12-12 11:40 UTC, MichaelOSullivanAnswer commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Logic.CreateDirectorySasToken.cs
> +                    inputContainer, inputDirectoryPath, inputAccessPolicyIdentifier),
updated

2024-12-12 11:40 UTC, MichaelOSullivanAnswer commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Storages/StorageTests.Exceptions.CreateDirectorySasToken.cs
> +                    someContainer, someDirectoryPath, someAccessPolicyIdentifier))
updated

2024-12-12 11:42 UTC, MichaelOSullivanAnswer commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Storages/StorageTests.Exceptions.CreateDirectorySasToken.cs
> +                broker.CreateDirectorySasTokenAsync(
Updated

2024-12-12 11:42 UTC, MichaelOSullivanAnswer commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Storages/StorageTests.Exceptions.CreateDirectorySasToken.cs
> +                    someContainer, someDirectoryPath, someAccessPolicyIdentifier);
Updated

2024-12-12 11:42 UTC, MichaelOSullivanAnswer commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Storages/StorageTests.Exceptions.CreateDirectorySasToken.cs
> +                    someContainer, someDirectoryPath, someAccessPolicyIdentifier))
Updated

2024-12-12 11:42 UTC, MichaelOSullivanAnswer commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Storages/StorageTests.Exceptions.CreateDirectorySasToken.cs
> +                    someContainer, someDirectoryPath, someAccessPolicyIdentifier);
Updated

2024-12-12 11:42 UTC, MichaelOSullivanAnswer commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Storages/StorageTests.Exceptions.CreateDirectorySasToken.cs
> +                    someContainer, someDirectoryPath, someAccessPolicyIdentifier),
Updated

2024-12-12 11:50 UTC, MichaelOSullivanAnswer commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Storages/StorageTests.Logic.CreateDirectorySasToken.cs
> +                inputContainer, inputDirectoryPath, inputAccessPolicyIdentifier);
Updated

2024-12-12 11:50 UTC, MichaelOSullivanAnswer commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Storages/StorageTests.Validations.CreateDirectorySasToken.cs
> +                    invalidContainer, invalidDirectoryPath, invalidAccessPolicyIdentifier);
Updated

2024-12-12 11:51 UTC, MichaelOSullivanAnswer commented on ISL.Providers.Storages.AzureBlobStorage/Services/Foundations/Storages/IStorageService.cs
> +             string container, string directoryPath, string accessPolicyIdentifier);
updated

2024-12-12 11:51 UTC, MichaelOSullivanAnswer commented on ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Storages/StorageTests.Exceptions.CreateDirectorySasToken.cs
> +                    someContainer, someDirectoryPath, someAccessPolicyIdentifier);
updated

2024-12-12 13:06 UTC, cjdutoit approved these changes

2024-12-12 13:06 UTC, merged